### ISSUE TITLE
dont work,

### ISSUE THREAD

**Issue by budgierless** [ahrasis/LE4ISPC#1]
maybe add checks, and its own log file. so I can work out what the issue is.

**my error log:**
Sep 11 02:52:33 mmg incrond[5834]: starting service (version 0.5.10, built on Nov  6 2014 06:51:22)
Sep 11 02:52:33 mmg incrond[5837]: loading system tables
Sep 11 02:52:33 mmg incrond[5837]: loading user tables
Sep 11 02:52:33 mmg incrond[5837]: ready to process filesystem events
Sep 11 02:52:33 mmg systemd[1]: Started file system events scheduler.
Sep 11 02:52:33 mmg systemd[1]: Reloading.
Sep 11 02:52:34 mmg systemd[1]: Started ACPI event daemon.
Sep 11 02:52:34 mmg systemd[1]: Started CUPS Scheduler.
Sep 11 02:52:37 mmg systemd[1]: Stopped LSB: Apache2 web server.
Sep 11 02:52:37 mmg systemd[1]: Starting LSB: Apache2 web server...
Sep 11 02:52:37 mmg apache2[5898]:  * Starting Apache httpd web server apache2
Sep 11 02:52:37 mmg apache2[5898]:  *
Sep 11 02:52:37 mmg apache2[5898]:  * The apache2 configtest failed.
Sep 11 02:52:37 mmg apache2[5898]: Output of config test was:
Sep 11 02:52:37 mmg apache2[5898]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:72
Sep 11 02:52:37 mmg apache2[5898]: AH00526: Syntax error on line 63 of /etc/apache2/sites-enabled/000-ispconfig.vhost:
Sep 11 02:52:37 mmg apache2[5898]: SSLCertificateFile: file '/usr/local/ispconfig/interface/ssl/ispserver.crt' does not exist or is empty
Sep 11 02:52:37 mmg apache2[5898]: Action 'configtest' failed.
Sep 11 02:52:37 mmg apache2[5898]: The Apache error log may have more information.
Sep 11 02:52:37 mmg systemd[1]: apache2.service: Control process exited, code=exited status=1
Sep 11 02:52:37 mmg systemd[1]: Failed to start LSB: Apache2 web server.
Sep 11 02:52:37 mmg systemd[1]: apache2.service: Unit entered failed state.
Sep 11 02:52:37 mmg systemd[1]: apache2.service: Failed with result 'exit-code'.
Sep 11 02:53:01 mmg CRON[5918]: (root) CMD (/usr/local/ispconfig/server/server.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:53:01 mmg CRON[5919]: (root) CMD (/usr/local/ispconfig/server/cron.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: warning: cannot get RSA certificate from file "/etc/postfix/smtpd.cert": disabling TLS support
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: warning: TLS library problem: error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/postfix/smtpd.cert','r'):
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: warning: TLS library problem: error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: warning: TLS library problem: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:701:
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: connect from unknown[195.22.127.206]
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: warning: Wrapper-mode request dropped from unknown[195.22.127.206] for service smtp. TLS context initialization failed. For details see earlier warnings in your logs.
Sep 11 02:53:41 mmg postfix/smtps/smtpd[5937]: disconnect from unknown[195.22.127.206] commands=0/0
Sep 11 02:53:53 mmg systemd[1]: Stopped LSB: Apache2 web server.
Sep 11 02:53:53 mmg systemd[1]: Starting LSB: Apache2 web server...
Sep 11 02:53:53 mmg apache2[5964]:  * Starting Apache httpd web server apache2
Sep 11 02:53:53 mmg apache2[5964]:  *
Sep 11 02:53:53 mmg apache2[5964]:  * The apache2 configtest failed.
Sep 11 02:53:53 mmg apache2[5964]: Output of config test was:
Sep 11 02:53:53 mmg apache2[5964]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:72
Sep 11 02:53:54 mmg apache2[5964]: AH00526: Syntax error on line 63 of /etc/apache2/sites-enabled/000-ispconfig.vhost:
Sep 11 02:53:54 mmg apache2[5964]: SSLCertificateFile: file '/usr/local/ispconfig/interface/ssl/ispserver.crt' does not exist or is empty
Sep 11 02:53:54 mmg apache2[5964]: Action 'configtest' failed.
Sep 11 02:53:54 mmg apache2[5964]: The Apache error log may have more information.
Sep 11 02:53:54 mmg systemd[1]: apache2.service: Control process exited, code=exited status=1
Sep 11 02:53:54 mmg systemd[1]: Failed to start LSB: Apache2 web server.
Sep 11 02:53:54 mmg systemd[1]: apache2.service: Unit entered failed state.
Sep 11 02:53:54 mmg systemd[1]: apache2.service: Failed with result 'exit-code'.
Sep 11 02:53:54 mmg systemd[1]: Stopped target Mail Transport Agent.
Sep 11 02:53:54 mmg systemd[1]: Stopping Mail Transport Agent.
Sep 11 02:53:54 mmg systemd[1]: Stopping LSB: Postfix Mail Transport Agent...
Sep 11 02:53:54 mmg postfix[5992]:  * Stopping Postfix Mail Transport Agent postfix
Sep 11 02:53:54 mmg postfix[6016]: Postfix is running with backwards-compatible default settings
Sep 11 02:53:54 mmg postfix[6016]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Sep 11 02:53:54 mmg postfix[6016]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Sep 11 02:53:54 mmg postfix/master[4867]: terminating on signal 15
Sep 11 02:53:54 mmg postfix[5992]:    ...done.
Sep 11 02:53:54 mmg systemd[1]: Stopped LSB: Postfix Mail Transport Agent.
Sep 11 02:53:54 mmg systemd[1]: Starting LSB: Postfix Mail Transport Agent...
Sep 11 02:53:54 mmg postfix[6026]:  * Starting Postfix Mail Transport Agent postfix
Sep 11 02:53:54 mmg postfix[6117]: Postfix is running with backwards-compatible default settings
Sep 11 02:53:54 mmg postfix[6117]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Sep 11 02:53:54 mmg postfix[6117]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Sep 11 02:53:55 mmg postfix[6026]:    ...done.
Sep 11 02:53:55 mmg systemd[1]: Started LSB: Postfix Mail Transport Agent.
Sep 11 02:53:55 mmg systemd[1]: Reached target Mail Transport Agent.
Sep 11 02:53:55 mmg postfix/master[6154]: /etc/postfix/master.cf: line 130: using backwards-compatible default setting chroot=y
Sep 11 02:53:55 mmg postfix/master[6154]: daemon started -- version 3.1.0, configuration /etc/postfix
Sep 11 02:53:55 mmg systemd[1]: Stopped Dovecot IMAP/POP3 email server.
Sep 11 02:53:55 mmg systemd[1]: Starting Dovecot IMAP/POP3 email server...
Sep 11 02:53:55 mmg dovecot[6165]: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 8: ssl_cert: Can't open file /etc/postfix/smtpd.cert: No such file or directory
Sep 11 02:53:55 mmg systemd[1]: dovecot.service: Control process exited, code=exited status=89
Sep 11 02:53:55 mmg systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
Sep 11 02:53:55 mmg systemd[1]: dovecot.service: Unit entered failed state.
Sep 11 02:53:55 mmg systemd[1]: dovecot.service: Failed with result 'exit-code'.
Sep 11 02:53:55 mmg systemd[1]: Stopping pure-ftpd-mysql.service...
Sep 11 02:53:55 mmg pure-ftpd-mysql[6181]: Stopping ftp server: pure-ftpd.
Sep 11 02:53:55 mmg systemd[1]: Stopped pure-ftpd-mysql.service.
Sep 11 02:53:55 mmg systemd[1]: Starting pure-ftpd-mysql.service...
Sep 11 02:53:55 mmg pure-ftpd-mysql[6195]: Starting ftp server: Running: /usr/sbin/pure-ftpd-mysql-virtualchroot -l mysql:/etc/pure-ftpd/db/mysql.conf -l pam -8 UTF-8 -b -O clf:/var/log/pure-ftpd/transfer.log -H -u 1000 -A -D -Y 1 -J ALL:!aNULL:!SSLv3 -E -B
Sep 11 02:53:55 mmg systemd[1]: Started pure-ftpd-mysql.service.
Sep 11 02:53:55 mmg pure-ftpd: (?@?) [ERROR] Sorry, but that file doesn't exist: [/etc/ssl/private/pure-ftpd.pem]
Sep 11 02:53:56 mmg systemd[1]: Stopped LSB: Apache2 web server.
Sep 11 02:53:56 mmg systemd[1]: Starting LSB: Apache2 web server...
Sep 11 02:53:56 mmg apache2[6228]:  * Starting Apache httpd web server apache2
Sep 11 02:53:56 mmg apache2[6228]:  *
Sep 11 02:53:56 mmg apache2[6228]:  * The apache2 configtest failed.
Sep 11 02:53:56 mmg apache2[6228]: Output of config test was:
Sep 11 02:53:56 mmg apache2[6228]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:72
Sep 11 02:53:56 mmg apache2[6228]: AH00526: Syntax error on line 63 of /etc/apache2/sites-enabled/000-ispconfig.vhost:
Sep 11 02:53:56 mmg apache2[6228]: SSLCertificateFile: file '/usr/local/ispconfig/interface/ssl/ispserver.crt' does not exist or is empty
Sep 11 02:53:56 mmg apache2[6228]: Action 'configtest' failed.
Sep 11 02:53:56 mmg apache2[6228]: The Apache error log may have more information.
Sep 11 02:53:56 mmg systemd[1]: apache2.service: Control process exited, code=exited status=1
Sep 11 02:53:56 mmg systemd[1]: Failed to start LSB: Apache2 web server.
Sep 11 02:53:56 mmg systemd[1]: apache2.service: Unit entered failed state.
Sep 11 02:53:56 mmg systemd[1]: apache2.service: Failed with result 'exit-code'.
Sep 11 02:54:01 mmg CRON[6247]: (root) CMD (/usr/local/ispconfig/server/cron.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:54:01 mmg CRON[6248]: (root) CMD (/usr/local/ispconfig/server/server.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:55:01 mmg CRON[6273]: (getmail) CMD (/usr/local/bin/run-getmail.sh > /dev/null 2>> /dev/null)
Sep 11 02:55:01 mmg CRON[6272]: (root) CMD (/usr/local/ispconfig/server/server.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:55:01 mmg CRON[6275]: (root) CMD (/usr/local/ispconfig/server/cron.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: warning: cannot get RSA certificate from file "/etc/postfix/smtpd.cert": disabling TLS support
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: warning: TLS library problem: error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/postfix/smtpd.cert','r'):
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: warning: TLS library problem: error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: warning: TLS library problem: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:701:
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: connect from localhost[::1]
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: warning: Wrapper-mode request dropped from localhost[::1] for service smtp. TLS context initialization failed. For details see earlier warnings in your logs.
Sep 11 02:55:02 mmg postfix/smtps/smtpd[6335]: disconnect from localhost[::1] commands=0/0
Sep 11 02:55:17 mmg kernel: [10639.439277] [Blocked CC]:IN=enp0s3 OUT= MAC=08:00:27:ff:33:f0:88:a6:c6:21:3f:b8:08:00 SRC=59.45.175.97 DST=81.138.252.212 LEN=60 TOS=0x00 PREC=0x00 TTL=46 ID=44218 DF PROTO=TCP SPT=49841 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
Sep 11 02:55:18 mmg kernel: [10640.439743] [Blocked CC]:IN=enp0s3 OUT= MAC=08:00:27:ff:33:f0:88:a6:c6:21:3f:b8:08:00 SRC=59.45.175.97 DST=81.138.252.212 LEN=60 TOS=0x00 PREC=0x00 TTL=46 ID=44219 DF PROTO=TCP SPT=49841 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
Sep 11 02:55:20 mmg kernel: [10642.441202] [Blocked CC]:IN=enp0s3 OUT= MAC=08:00:27:ff:33:f0:88:a6:c6:21:3f:b8:08:00 SRC=59.45.175.97 DST=81.138.252.212 LEN=60 TOS=0x00 PREC=0x00 TTL=46 ID=44220 DF PROTO=TCP SPT=49841 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
Sep 11 02:55:22 mmg kernel: [10644.449431] [Blocked CC]:IN=enp0s3 OUT= MAC=08:00:27:ff:33:f0:88:a6:c6:21:3f:b8:08:00 SRC=59.45.175.97 DST=81.138.252.212 LEN=60 TOS=0x00 PREC=0x00 TTL=46 ID=37767 DF PROTO=TCP SPT=39313 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
Sep 11 02:55:23 mmg kernel: [10645.463220] [Blocked CC]:IN=enp0s3 OUT= MAC=08:00:27:ff:33:f0:88:a6:c6:21:3f:b8:08:00 SRC=59.45.175.97 DST=81.138.252.212 LEN=60 TOS=0x00 PREC=0x00 TTL=46 ID=37768 DF PROTO=TCP SPT=39313 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
Sep 11 02:56:01 mmg CRON[6353]: (root) CMD (/usr/local/ispconfig/server/cron.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:56:01 mmg CRON[6354]: (root) CMD (/usr/local/ispconfig/server/server.sh 2>&1 | while read line; do echo `/bin/date` "$line" >> /var/log/ispconfig/cron.log; done)
Sep 11 02:56:21 mmg systemd[1]: Started Session 415 of user root.

**Comment by ahrasis** [comment]
> Sep 11 02:53:54 mmg apache2[5964]: SSLCertificateFile: file '/usr/local/ispconfig/interface/ssl/ispserver.crt' does not exist or is empty

I think you did not enable SSL for ISPConfig or did not enable LE for ISPConfig website thereafter before using this script. You don't simply use this script without the above have been successfully enabled first.

**Comment by budgierless** [comment]
I already installed ispconfig with ssl with I followed in the 16.04 tutorial, if that is what you mean.
Is their a way you could add a check system to the script for it to detect what is enabled or missing because at the moment their is no of knowing without searing the system logs if something is wrong.

**Comment by ahrasis** [comment]
Despite your arguments, the error log as I quoted above from your earlier posting says otherwise. Anyway, you can modify the script as you want before using it as it is not meant for special case but just a general one.
