### ISSUE TITLE
After Run LE4ISPC not work url right for phpmyadmin

### ISSUE THREAD

**Issue by BarbaraEster** [ahrasis/LE4ISPC#10]
Hello! After run LE4ISPC, i have a problem with the phpmyadmin.
I see that sub.dominio.com/phpmyadmin 1 not work
but dominio.com/phpmyadmin 1 work for me. Oo

And my host is:
root@server:~# hostname -f
server.ispvultr.tk

concluding the url >>> server.ispvultr.tk/phpmyadmin not work.
Just ispvultr.tk/phpmyadmin that work.

Thx

**Comment by ahrasis** [comment]
Your https://server.ispvultr.tk:8080 is working fine as such LE4ISPC works correctly.

**Comment by BarbaraEster** [comment]
My apps.vhost in apache2
`
Listen 8081
# NameVirtualHost *:8081

<VirtualHost _default_:8081>
  ServerAdmin webmaster@localhost


  <FilesMatch "\.ph(p3?|tml)$">
    SetHandler None
  </FilesMatch>

  <IfModule mod_headers.c>
        RequestHeader unset Proxy early
  </IfModule>


  <IfModule mod_php5.c>
    DocumentRoot /var/www/apps
    AddType application/x-httpd-php .php
    <Directory /var/www/apps>
                Options FollowSymLinks
                AllowOverride None
                                Require all granted
                    </Directory>
  </IfModule>

  <IfModule mod_php7.c>
    DocumentRoot /var/www/apps
    AddType application/x-httpd-php .php
    <Directory /var/www/apps>
                Options FollowSymLinks
                AllowOverride None
                                Require all granted
                    </Directory>
  </IfModule>

  <IfModule mod_fcgid.c>
    DocumentRoot /var/www/apps
    SuexecUserGroup ispapps ispapps
    <Directory /var/www/apps>
                Options +Indexes +FollowSymLinks +MultiViews +ExecCGI
                AllowOverride AuthConfig Indexes Limit Options FileInfo
                <FilesMatch "\.php$">
                        SetHandler fcgid-script
                </FilesMatch>
                FCGIWrapper /var/www/php-fcgi-scripts/apps/.php-fcgi-starter .php
                                Require all granted
                    </Directory>
  </IfModule>


</VirtualHost>
`

Thx, i run the code and just this work>>

root@server:/# ls -lath /etc/letsencrypt//$(hostname -f)
ls: cannot access '/etc/letsencrypt//server.ispvultr.tk': No such file or directory

and secound command

`root@server:/# ls -lath /usr/local/ispconfig/interface/ssl/ispserver.*
lrwxrwxrwx 1 root root   54 Sep 10 20:05 /usr/local/ispconfig/interface/ssl/ispserver.crt -> /etc/letsencrypt/live/server.ispvultr.tk/fullchain.pem
lrwxrwxrwx 1 root root   52 Sep 10 20:05 /usr/local/ispconfig/interface/ssl/ispserver.key -> /etc/letsencrypt/live/server.ispvultr.tk/privkey.pem
-rw------- 1 root root 5.2K Sep 10 20:05 /usr/local/ispconfig/interface/ssl/ispserver.pem
-rw------- 1 root root    0 Sep 10 19:54 /usr/local/ispconfig/interface/ssl/ispserver.pem-190910200523.bak
-rwxr-x--- 1 root root 3.2K Sep 10 16:06 /usr/local/ispconfig/interface/ssl/ispserver.key-190910200523.bak
-rwxr-x--- 1 root root 2.0K Sep 10 16:06 /usr/local/ispconfig/interface/ssl/ispserver.crt-190910200523.bak
-rwxr-x--- 1 root root 1.7K Sep 10 16:06 /usr/local/ispconfig/interface/ssl/ispserver.csr
-rwxr-x--- 1 root root 3.3K Sep 10 16:06 /usr/local/ispconfig/interface/ssl/ispserver.key.secure
`

**Comment by ahrasis** [comment]
Your ISPConfig server has its LE SSL certs but you might have set your phpmyadmin wrongly or in the wrong vhost. Check in which vhost did you enable phpmyadmin. It should be enabled without any domain or with server.ispvultr.tk, if you intend to securely access only from that domain.

**Comment by BarbaraEster** [comment]
Hello! After one day, the my domain normal ispvultr.tk not work more ssl, just with port 8080. Oo
Is strange.

**Comment by BarbaraEster** [comment]
Hello he back https, after restart the apache2 Oo
