### ISSUE TITLE
Script does not work for most recent Debian 10 ISPconfig tutorial on howtoforge.

### ISSUE THREAD

**Issue by lucatze** [ahrasis/LE4ISPC#12]
Solution: Replacing certbot with certbot-auto in the entire script did the trick for me.

**Comment by nanoarmando** [comment]
Me too

**Comment by flomojoe** [comment]
This do not fix the issue: ... le4ispc.sh: line 28: certbot-auto: command not found.
Thank you for feedback ...

**Comment by ahrasis** [comment]
All issues are closed as ISPConfig 3.2 already integrated this. Remove LE4ISPC using the script and choose SSL during upgrade to ISPConfig 3.2.
