### ISSUE TITLE
script fails when postfix installed and dovecot not

### ISSUE THREAD

**Issue by degoya** [ahrasis/LE4ISPC#6]
i got a multiserver setup on debian9 with one server that got postfix installed but not dovecot.
if i use the script it fails because it trys to restart dovecot with the error:
Failed to restart dovecot.service: Unit dovecot.service not found.
if i comment them out it works once but with the autoupdate it gets always replaced, would be great to have a detection for dovecot included.

**Comment by ahrasis** [comment]
Noted that and fixed. Thank you.
