### ISSUE TITLE
Remove --no-check-certificate from tutorial recipe

### ISSUE THREAD

**Issue by schoen** [ahrasis/LE4ISPC#9]
Hi! I would like to suggest removing the `--no-check-certificate` from the `wget` command in your tutorial. This option is dangerous in general, and especially so when downloading software to run, because it allows the ISP to change the content of the downloaded file with no warning.

Since `raw.githubusercontent.com` has a valid publicly-trusted certificate, the `--no-check-certificate` isn't useful to users on most networks. (If there are some users on networks who do need to use this option, they should have some other way available to verify the content of the downloaded script before running it, such as a SHA-256 hash.)

**Comment by ahrasis** [comment]
Done.
